### ISSUE TITLE
Some Package Conflict and Solution 

### ISSUE THREAD

**Issue by XuXinhangNTU** [LeCAR-Lab/dial-mpc#11]
First Thanks to your amazing works!
So I find some package version conflict that may cause crush after following the installation guidance.

For successfully run the Synchronous Simulation, in json.py the line  132    
need change the 
`if (rgba == [0.5, 0.5, 0.5, 1.0]).all():   ->    if jp.array_equal(rgba, jp.array([0.5, 0.5, 0.5, 1.0])):`

to avoid the error

```
Processing rollout for visualization
Traceback (most recent call last):
  File "/usr/local/bin/dial-mpc", line 33, in <module>
    sys.exit(load_entry_point('dial-mpc', 'console_scripts', 'dial-mpc')())
  File "/root/dial-mpc/dial_mpc/core/dial_core.py", line 290, in main
    webpage = html.render(
  File "/usr/local/lib/python3.10/dist-packages/brax/io/html.py", line 76, in render
    return render_from_json(json.dumps(sys, states), height, colab, base_url)
  File "/usr/local/lib/python3.10/dist-packages/brax/io/json.py", line 132, in dumps
    if (rgba == [0.5, 0.5, 0.5, 1.0]).all():
  File "/usr/local/lib/python3.10/dist-packages/jax/_src/numpy/array_methods.py", line 577, in deferring_binary_op
    raise TypeError(f"unsupported operand type(s) for {opchar}: "
TypeError: unsupported operand type(s) for ==: 'ArrayImpl' and 'list'
```

For successfully run the Asynchronous Simulation

**The mojuco package should be <=3.2.4 because the mojuco.mjv_makeConnector is deprecated in version 3.2.5
Also the mujoco-mjx should change version to the corresponding mujuco package**
To avoid 

```
Traceback (most recent call last):
  File "/usr/local/bin/dial-mpc-sim", line 33, in <module>
    sys.exit(load_entry_point('dial-mpc', 'console_scripts', 'dial-mpc-sim')())
  File "/root/dial-mpc/dial_mpc/deploy/dial_sim.py", line 347, in main
    mujoco_env.main_loop()
  File "/root/dial-mpc/dial_mpc/deploy/dial_sim.py", line 192, in main_loop
    mujoco.mjv_makeConnector(
AttributeError: module 'mujoco' has no attribute 'mjv_makeConnector'. Did you mean: 'mjv_connector'?

```
And I also contribute a docker, feel free to play!

` docker pull xuxinhang007/dialmpc:v1`

**Comment by huihuaNvidia2023** [comment]
Hi @XuXinhangNTU, thanks for your docker image and installation tips. It's very helpful. Do you mind share your docker file?

**Comment by XuXinhangNTU** [comment]
Hi @huihuaNvidia2023  the docker image is public. Do you mean the .DockerFile ? I use docker commit to create the docker image,  so I don’t prepare a DockerFile now. If you are interested in it, I can make it later.

**Comment by XuXinhangNTU** [comment]
@huihuaNvidia2023  Okay, but this week is busy. I will do it later and when I finish, I will upload it. Thx!

**Comment by huihuaNvidia2023** [comment]
Thanks, not in a hurry. I got it working locally after I post the first question. To run in the Synchronous, I actually don't need to update the `json.py` as you mentioned.

**Comment by XuXinhangNTU** [comment]
@ huihuaNvidia2023 It may be my docker environment Python version issue. Anyway, if you can let it run, that is good news. 😊

**Comment by HaoruXue** [comment]
ah thank you all for the discussion around the issue.

`mjv_makeConnector` is really just used for making the trajectory visualization. It should be fine to even just comment this out if people wants to use 3.2.5. But yeah I'll add a constraint to `setup.py`, since otherwise there are no benifits for switching to 3.2.5 (I guess we are all waiting on the mujoco-mjx's supposedly big updates comming up at this point 👀)

@XuXinhangNTU @huihuaNvidia2023 thanks for the discussion around the dockerfile too! Do you feel like opening a PR to include that in this upstream repo?

**Comment by HaoruXue** [comment]
@XuXinhangNTU @huihuaNvidia2023 any updates on whether you would be able to contribute a PR for the dockerfile?

**Comment by huihuaNvidia2023** [comment]
Hi @HaoruXue, I didn't use any docker for my trial.

**Comment by XuXinhangNTU** [comment]
> [@XuXinhangNTU](https://github.com/XuXinhangNTU) [@huihuaNvidia2023](https://github.com/huihuaNvidia2023) any updates on whether you would be able to contribute a PR for the dockerfile? 😀

Hi, Haoru, I will pub it before CNY! Still busy these days.

**Comment by HaoruXue** [comment]
> > [@XuXinhangNTU](https://github.com/XuXinhangNTU) [@huihuaNvidia2023](https://github.com/huihuaNvidia2023) any updates on whether you would be able to contribute a PR for the dockerfile? 😀
> 
> Hi, Haoru, I will pub it before CNY! Still busy these days.

Sounds good! Looking forward to it.

**Comment by XuXinhangNTU** [comment]
> > > [@XuXinhangNTU](https://github.com/XuXinhangNTU) [@huihuaNvidia2023](https://github.com/huihuaNvidia2023) any updates on whether you would be able to contribute a PR for the dockerfile? 😀
> > 
> > 
> > Hi, Haoru, I will pub it before CNY! Still busy these days.
> 
> Sounds good! Looking forward to it.

Hi Haoru this is the rp link https://github.com/XuXinhangNTU/dial-mpc-docker
I dont know whether this is what you want, if u wanna me add something or delete something, just tell me! @HaoruXue

**Comment by HaoruXue** [comment]
@XuXinhangNTU Thank you for the effort. Feel free to create a PR and put it under `docker/` folder in this repo. I'll follow up to clean up the image file, CI, and something like [Rocker](https://github.com/osrf/rocker) to make the launching experience better.

**Comment by XuXinhangNTU** [comment]
Hi @HaoruXue, sorry for misunderstanding what is a PR hahaha. At beginning, I thought PR is personal repo, a friend just told me PR is Pull Request. I have already sent the request, Happy new year!

**Comment by tc2882** [comment]
Hi @XuXinhangNTU , what is the version of jax and brax should I use? 

I got the follow error:

```
🚀Creating environment
/home/linux/anaconda3/envs/dial-mpc/lib/python3.10/site-packages/brax/io/mjcf.py:480: UserWarning: Brax System, piplines and environments are not actively being maintained. Please see MJX for a well maintained JAX-based physics engine: https://github.com/google-deepmind/mujoco/tree/main/mjx. For a host of environments that use MJX, see: https://github.com/google-deepmind/mujoco_playground.
  warnings.warn(
[0.5904899  0.6560999  0.7289999  0.80999994 0.9        1.        ]
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/linux/anaconda3/envs/dial-mpc/bin/dial-mpc-plan", line 33, in <module>
    sys.exit(load_entry_point('dial-mpc', 'console_scripts', 'dial-mpc-plan')())
  File "/home/linux/dial-mpc/dial_mpc/deploy/dial_plan.py", line 288, in main
    mbd_publisher.main_loop()
  File "/home/linux/dial-mpc/dial_mpc/deploy/dial_plan.py", line 165, in main_loop
    state = self.init_mjx_state(
  File "/home/linux/dial-mpc/dial_mpc/deploy/dial_plan.py", line 143, in init_mjx_state
    pipeline_state = self.pipeline_init_jit(self.env.sys, q, qd)
  File "/home/linux/dial-mpc/dial_mpc/deploy/dial_plan.py", line 60, in pipeline_init
    data = _reformat_contact(sys, data)
  File "/home/linux/anaconda3/envs/dial-mpc/lib/python3.10/site-packages/brax/mjx/pipeline.py", line 32, in _reformat_contact
    elasticity = jp.zeros(contact.pos.shape[0])
AttributeError: 'Data' object has no attribute 'pos'. Did you mean: 'qpos'?
/home/linux/anaconda3/envs/dial-mpc/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 6 leaked shared_memory objects to clean up at shutdown


``` 
Thank you very much!
