### ISSUE TITLE
JAX `ValueError: mutable default <class 'jaxlib.xla_extension.ArrayImpl'> for field kp is not allowed: use default_factory` for unitree_h1_env

### ISSUE THREAD

**Issue by Mr-Zqr** [LeCAR-Lab/dial-mpc#3]
Hi, 

Thanks so much for such inspiring work and the open-source!

I'm running `dial-mpc --list-examples` and encountered an error that seems to relate to file `unitree_h1_env.py` and the Jax library. Here is the terminal output: 
``` bash
$ dial-mpc --list-examples
2024-09-27 14:14:55.646980: W external/xla/xla/service/gpu/nvptx_compiler.cc:893] The NVIDIA driver's CUDA version is 12.4 which is older than the PTX compiler version 12.6.68. Because the driver is older than the PTX compiler version, XLA is disabling parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provided CUDA forward compatibility packages.
Traceback (most recent call last):
  File "/home/zqr/anaconda3/envs/dial_mpc/bin/dial-mpc", line 33, in <module>
    sys.exit(load_entry_point('dial-mpc', 'console_scripts', 'dial-mpc')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zqr/anaconda3/envs/dial_mpc/bin/dial-mpc", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/zqr/anaconda3/envs/dial_mpc/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zqr/anaconda3/envs/dial_mpc/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/zqr/devel/src/dial-mpc/dial_mpc/core/dial_core.py", line 23, in <module>
    import dial_mpc.envs as dial_envs
  File "/home/zqr/devel/src/dial-mpc/dial_mpc/envs/__init__.py", line 2, in <module>
    from dial_mpc.envs.unitree_h1_env import (
  File "/home/zqr/devel/src/dial-mpc/dial_mpc/envs/unitree_h1_env.py", line 25, in <module>
    @dataclass
     ^^^^^^^^^
  File "/home/zqr/anaconda3/envs/dial_mpc/lib/python3.12/dataclasses.py", line 1275, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/home/zqr/anaconda3/envs/dial_mpc/lib/python3.12/dataclasses.py", line 1265, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zqr/anaconda3/envs/dial_mpc/lib/python3.12/dataclasses.py", line 994, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zqr/anaconda3/envs/dial_mpc/lib/python3.12/dataclasses.py", line 852, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'jaxlib.xla_extension.ArrayImpl'> for field kp is not allowed: use default_factory
```
I found that the configuration `kp` and `kd` for Unitree H1 is a `jnp.array` while for Unitree Go2 is a number, after changing `jnp.array()` to 200, the error stopped and the system runs perfectly. 

However, I am completely new to Python and Jax so this definitely is not the right way to solve this problem. Therefore I am raising this issue to find better solutions or to see if I have done something wrong with the environment configuration. 

Here are my system configurations: 
- OS: Ubuntu 20.04
- Python: 3.12, using anaconda
- GPU: NVIDIA RTX 2060
- CUDA version: 12.4

**Comment by HaoruXue** [comment]
Ah - I guess dataclass changes its behavior in 3.12.

Our setup is Ubuntu 22.04 + Python 3.10.

Yeah please use 3.10 for now and give us some time to fully test against other python versions.

Thanks for reporting!

**Comment by Mr-Zqr** [comment]
Yeah, changing to Python 3.10 fixed it, thanks a lot!

**Comment by HaoruXue** [comment]
Update - #4 should have fixed this issue.
